# Generated by Django 5.1.7 on 2025-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(related_name='ads', to='board.category'),
        ),
    ]
