# Generated by Django 4.2.20 on 2025-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
