# Generated by Django 4.2.20 on 2025-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_server_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
    ]
