# Generated by Django 4.2.20 on 2025-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_server_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
