# Generated by Django 4.2.20 on 2025-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_server_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='user_name',
            field=models.CharField(max_length=120),
        ),
    ]
