# Generated by Django 4.2.20 on 2025-05-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_server_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='health',
        ),
        migrations.AddField(
            model_name='server',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
