# Generated by Django 4.2.20 on 2025-05-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_server_health_server_phone_server_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tg_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
