# Generated by Django 4.2.20 on 2025-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_server_tg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tg_id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='monuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monuser',
            name='tg_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
