# Generated by Django 4.2.20 on 2025-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_server_phone_remove_server_tg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='monuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
