# Generated by Django 4.2.20 on 2025-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_monuser_username_alter_monuser_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='free_disk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='free_memory',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
