# Generated by Django 4.2.20 on 2025-05-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_server_cpu_load_server_free_disk_server_free_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu_load',
        ),
        migrations.RemoveField(
            model_name='server',
            name='free_disk',
        ),
        migrations.RemoveField(
            model_name='server',
            name='free_memory',
        ),
    ]
