# Generated by Django 5.1.7 on 2025-04-03 15:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', upload_to=blog.models.user_photo_path),
        ),
    ]
